### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'remove'

### ISSUE THREAD

**Issue by mathieumd** [jflesch/paperwork#511]
I just upgraded to 1.0, and cannot launch paperwork anymore:

```
$ paperwork
INFO   paperwork.paperwork            Using locales in '/usr/share/locale'
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane_lP1xWM/pipe_c2s | /tmp/pyinsane_lP1xWM/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file found: /home/mathieu/.config/paperwork.conf
INFO   paperwork_backend.config       Reloading /home/mathieu/.config/paperwork.conf ...

(paperwork:11909): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(paperwork:11909): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(paperwork:11909): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 118, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2075, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2623, in __init_app_menu
    menu.remove(0)
AttributeError: 'NoneType' object has no attribute 'remove'
```

I am using KDE on Debian testing.

Note: I had to install the package `python-configparser` to pass through this error:

```
$ paperwork
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 3, in <module>
    from paperwork.paperwork import main
  File "/usr/local/lib/python2.7/dist-packages/paperwork/paperwork.py", line 42, in <module>
    from .frontend.mainwindow import ActionRefreshIndex, MainWindow
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 54, in <module>
    from paperwork.frontend.multiscan import MultiscanDialog
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/multiscan/__init__.py", line 32, in <module>
    from paperwork.frontend.util.config import get_scanner
  File "/usr/local/lib/python2.7/dist-packages/paperwork/frontend/util/config.py", line 17, in <module>
    import configparser
ImportError: No module named configparser
```

**Comment by jflesch** [comment]
You started Paperwork with Python 2.7 instead of Python 3.
The documentation wasn't up-to-date. I fixed it this morning (it's 11pm here now). Sorry.

**Comment by jflesch** [comment]
Can you give me the output of ```pip3 show pycountry``` please ?

**Comment by mathieumd** [comment]
Thanks for your quick reply. You don't need to apologize!

Unfortunately, my problem seems to still be the same. I did `sudo pip uninstall paperwork` then `sudo pip3 install paperwork`. Both `paperwork-shell chkdeps` said `All dependencies have been found.`, but still:

```
$ paperwork
INFO   paperwork.paperwork            Using locales in '/usr/share/locale'
INFO   pyinsane2.sane.abstract_proc   Starting Pyinsane subprocess
INFO   pyinsane2.sane.abstract_proc   Pyinsane pipes: /tmp/pyinsane__jpn0m7s/pipe_c2s | /tmp/pyinsane__jpn0m7s/pipe_s2c
INFO   pyinsane2.sane.abstract_proc   Connected to Pyinsane subprocess
INFO   paperwork_backend.config       Config file found: /home/mathieu/.config/paperwork.conf
INFO   paperwork_backend.config       Reloading /home/mathieu/.config/paperwork.conf ...

(paperwork:24404): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(paperwork:24404): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(paperwork:24404): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
INFO   paperwork.frontend.util        UI file used: /usr/share/paperwork/mainwindow/appmenu.xml
INFO   paperwork.paperwork            Good bye
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 6, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/paperwork/paperwork.py", line 118, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2075, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/usr/local/lib/python3.5/dist-packages/paperwork/frontend/mainwindow/__init__.py", line 2623, in __init_app_menu
    menu.remove(0)
AttributeError: 'NoneType' object has no attribute 'remove'
```

You initially asked for `pip3 show pycountry`, here it is:

```
---
Metadata-Version: 2.0
Name: pycountry
Version: 16.11.8
Summary: ISO country, subdivision, language, currency and script definitions and their translations
Home-page: UNKNOWN
Author: Christian Theune
Author-email: ct@flyingcircus.io
Installer: pip
License: LGPL 2.1
Location: /usr/local/lib/python3.5/dist-packages
Requires:
Classifiers:
  Development Status :: 5 - Production/Stable
  Intended Audience :: Developers
  Intended Audience :: Information Technology
  License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Topic :: Software Development :: Internationalization
  Topic :: Software Development :: Localization
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by jflesch** [comment]
Sorry, the pycountry request was for another ticket ... :)

1) How did you install Paperwork exactly ?
2) Can you post a copy of your '/usr/share/paperwork/mainwindow/appmenu.xml' here please ? (btw, I just realized it should be installed in /usr/local -- #513)

**Comment by mathieumd** [comment]
> 1) How did you install Paperwork exactly ?

A long time ago, I may have installed it through `git clone` (if it was actually a possible installation method, I really don't remember... :-/). Then, a few months ago, I installed it through `sudo pip install paperwork`, but uninstalled it today, then ran the `sudo pip3 install paperwork`.

> 2) Can you post a copy of your '/usr/share/paperwork/mainwindow/appmenu.xml' here please ? (btw, I just realized it should be installed in /usr/local -- #513)

File date is 2016-02-16, which may be the day I installed it first through pip (or not, I don't remember at all). Should have it been replaced by 1.0?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
        <menu id="menubar">
                <submenu id="app-menu">
                        <attribute name="label" translatable="yes">_File</attribute>
                        <section>
                                <item>
                                        <attribute name="label" translatable="yes">_Settings</attribute>
                                        <attribute name="action">app.settings</attribute>
                                </item>
                        </section>
                        <section>
                                <submenu id="advanced">
                                        <attribute name="label" translatable="yes">_Advanced</attribute>
                                        <item>
                                                <attribute name="label" translatable="yes">Optimize index</attribute>
                                                <attribute name="action">app.optimize_index</attribute>
                                        </item>
                                        <item>
                                                <attribute name="label" translatable="yes">Reindex all the documents</attribute>
                                                <attribute name="action">app.reindex_all</attribute>
                                        </item>
                                        <item>
                                                <attribute name="label" translatable="yes">Redo OCR on all the documents</attribute>
                                                <attribute name="action">app.redo_ocr_all</attribute>
                                        </item>
                                </submenu>
                        </section>
                        <section>
                                <item>
                                        <attribute name="label" translatable="yes">_About</attribute>
                                        <attribute name="action">app.about</attribute>
                                </item>
                                <item>
                                        <attribute name="label" translatable="yes">_Quit</attribute>
                                        <attribute name="action">app.quit</attribute>
                                </item>
                        </section>
                </submenu>
        </menu>
</interface>
```

**Comment by jflesch** [comment]
Ok I understand now. One of the main problems with Pip is that is tends to keep old versions as well as new. It makes sense for library (program may required specific versions of libraries), but it doesn't for programs and create problems with data files.

What you can try:

```
sudo pip3 uninstall paperwork  # many times, until it says it's not installed anymore
sudo pip3 uninstall paperwork-backend  # many times, until it says it's not installed anymore
sudo pip uninstall paperwork  # many times, until it says it's not installed anymore

sudo pip3 install paperwork # just once ;)
```

**Comment by jflesch** [comment]
I will update the documentation

**Comment by mathieumd** [comment]
OK, it's fixed.

All `uninstall` commands were successful at first run (every next runs returns `Cannot uninstall requirement paperwork, not installed`).

But what made the difference, was to remove the folder `/usr/share/paperwork`. Now it runs well, and I can see the fun airplane origami paper. :)

Thanks for your help! And for Papercut also, of course!

**Comment by jflesch** [comment]
You're welcome, and thank you for taking the time to report this problem :)
